//! A small, replayable learner corpus for independently generated finite G0
//! worlds.
//!
//! The term compiler owns world generation and semantic admission. This crate
//! owns the narrow learner boundary: every admitted world becomes one audited
//! G0 transcript and one serializable token stream. Train and held-out worlds
//! are generated by separate specs and are disjoint by semantic hash.

use std::collections::{BTreeMap, BTreeSet};

use pretraining_g0_contract::optimal_actions_from;
use pretraining_g0_render::{
    boundary_check, profiled_tokens, BoundarySubtype, Content, G0Episode, G0Fact, G0Group,
    KeyNamespace, Port, PortSchema, RenderFault,
};
use pretraining_term_compiler::{
    CompileError, G0CorpusSpec, GeneratedWorld, GoalPredicate, PortValue, PublicBoundary,
    PublicEvent, PublicEventGroup, PublicEventTime, PublicEventValue, PublicPortDescriptor,
    PublicTransitionTable, SymbolicGoalDiagnostic,
};
use pretraining_world::{LearningToken, Role, Supervision, ACTION_HORIZON, PAYLOAD_DIM};
use serde::{Deserialize, Serialize};

/// Scheduling/evaluation metadata. It is removed by [`CorpusArtifact::learner_tokens`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum Split {
    Train,
    HeldOut,
}

/// Serializable form of the production learner token. The production token
/// intentionally has no persistence contract, so the artifact uses primitive
/// role and payload fields while retaining the exact ABI widths.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CorpusToken {
    pub role: u8,
    pub key: u16,
    pub event: u16,
    pub payload: [f32; PAYLOAD_DIM],
    pub action_target: [f32; ACTION_HORIZON],
    pub action_mask: [bool; ACTION_HORIZON],
    pub future_target: f32,
    pub future_mask: bool,
}

impl From<&LearningToken> for CorpusToken {
    fn from(token: &LearningToken) -> Self {
        Self {
            role: token.public.role as u8,
            key: token.public.key,
            event: token.public.event,
            payload: token.public.payload,
            action_target: token.supervision.action_target,
            action_mask: token.supervision.action_mask,
            future_target: token.supervision.future_target,
            future_mask: token.supervision.future_mask,
        }
    }
}

impl CorpusToken {
    /// Convert the artifact form back to the production learner boundary.
    /// Unknown roles fail instead of silently becoming padding.
    pub fn learning_token(&self) -> Result<LearningToken, CorpusError> {
        let role = match self.role {
            0 => Role::Pad,
            1 => Role::SchemaObservation,
            2 => Role::SchemaActuator,
            3 => Role::Boundary,
            4 => Role::Condition,
            5 => Role::Goal,
            6 => Role::Observation,
            7 => Role::ActionQuery,
            8 => Role::ActionExecuted,
            9 => Role::FutureQuery,
            10 => Role::Feedback,
            role => return Err(CorpusError::Invalid(format!("unknown learner role {role}"))),
        };
        Ok(LearningToken {
            public: pretraining_world::PublicToken {
                role,
                key: self.key,
                event: self.event,
                payload: self.payload,
            },
            supervision: Supervision {
                action_target: self.action_target,
                action_mask: self.action_mask,
                future_target: self.future_target,
                future_mask: self.future_mask,
            },
        })
    }
}

/// One generated world with its public transcript and learner-facing records.
/// Generator coordinates and semantic hashes are metadata, not token fields.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CorpusExample {
    pub split: Split,
    pub semantic_hash: String,
    pub generator_seed: u64,
    pub generator_index: usize,
    /// Exact shortest non-fallback success length realized by this world.
    /// This is persisted so corpus consumers can inspect the realized target
    /// distribution without re-running privileged world queries.
    pub plan_length: usize,
    pub episode: G0Episode,
    pub tokens: Vec<CorpusToken>,
    pub fingerprint: u64,
}

impl CorpusExample {
    pub fn learning_tokens(&self) -> Result<Vec<LearningToken>, CorpusError> {
        self.tokens
            .iter()
            .map(CorpusToken::learning_token)
            .collect()
    }
}

/// The persisted first-stage corpus. One example corresponds to one generated
/// world; no embodiment-control triples or family aliases are introduced here.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CorpusArtifact {
    pub schema_version: u16,
    pub train_spec: G0CorpusSpec,
    pub held_out_spec: G0CorpusSpec,
    pub examples: Vec<CorpusExample>,
}

impl CorpusArtifact {
    pub const SCHEMA_VERSION: u16 = 2;

    pub fn train(&self) -> impl Iterator<Item = &CorpusExample> {
        self.examples
            .iter()
            .filter(|example| example.split == Split::Train)
    }

    pub fn held_out(&self) -> impl Iterator<Item = &CorpusExample> {
        self.examples
            .iter()
            .filter(|example| example.split == Split::HeldOut)
    }

    /// Drop split, world, and generator metadata at the learner handoff.
    pub fn learner_tokens(&self, split: Split) -> Result<Vec<LearningToken>, CorpusError> {
        self.examples
            .iter()
            .filter(|example| example.split == split)
            .try_fold(Vec::new(), |mut tokens, example| {
                tokens.extend(example.learning_tokens()?);
                Ok(tokens)
            })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CorpusError {
    Invalid(String),
    UnsupportedPublicEvent(String),
    Compile(String),
    Render(String),
    StructuralOverlap { semantic_hash: String },
}

impl std::fmt::Display for CorpusError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Invalid(message) => write!(f, "invalid G0 corpus: {message}"),
            Self::UnsupportedPublicEvent(message) => {
                write!(f, "unsupported public G0 event: {message}")
            }
            Self::Compile(message) => write!(f, "G0 corpus compilation failed: {message}"),
            Self::Render(message) => write!(f, "G0 corpus rendering failed: {message}"),
            Self::StructuralOverlap { semantic_hash } => write!(
                f,
                "train and held-out splits share semantic world {semantic_hash}"
            ),
        }
    }
}

impl std::error::Error for CorpusError {}

impl From<CompileError> for CorpusError {
    fn from(error: CompileError) -> Self {
        Self::Compile(error.to_string())
    }
}

impl From<RenderFault> for CorpusError {
    fn from(error: RenderFault) -> Self {
        Self::Render(error.to_string())
    }
}

/// Generate deterministic train and held-out streams. Overlap is refused
/// rather than silently weakening the held-out claim.
pub fn generate_corpus(
    train_spec: G0CorpusSpec,
    held_out_spec: G0CorpusSpec,
) -> Result<CorpusArtifact, CorpusError> {
    let train_worlds = train_spec.generate()?;
    let held_out_worlds = held_out_spec.generate()?;
    let train_hashes: BTreeSet<String> = train_worlds
        .iter()
        .map(|world| world.term.family_hash())
        .collect();
    for world in &held_out_worlds {
        let semantic_hash = world.term.family_hash();
        if train_hashes.contains(&semantic_hash) {
            return Err(CorpusError::StructuralOverlap { semantic_hash });
        }
    }

    let mut examples = Vec::with_capacity(train_worlds.len() + held_out_worlds.len());
    append_worlds(&mut examples, Split::Train, &train_worlds)?;
    append_worlds(&mut examples, Split::HeldOut, &held_out_worlds)?;
    Ok(CorpusArtifact {
        schema_version: CorpusArtifact::SCHEMA_VERSION,
        train_spec,
        held_out_spec,
        examples,
    })
}

fn append_worlds(
    examples: &mut Vec<CorpusExample>,
    split: Split,
    worlds: &[GeneratedWorld],
) -> Result<(), CorpusError> {
    for world in worlds {
        let compiled = world.compile()?;
        let plan_length = compiled
            .shortest_optimal_non_fallback_plan_length()
            .ok_or_else(|| {
                CorpusError::Invalid(format!(
                    "generated world {} has no non-fallback success plan",
                    world.generator_metadata.index
                ))
            })?;
        let episode = episode_for(&compiled)?;
        let evidence = boundary_check(&episode)?;
        let tokens = profiled_tokens(&episode)?
            .iter()
            .map(CorpusToken::from)
            .collect();
        examples.push(CorpusExample {
            split,
            semantic_hash: world.term.family_hash(),
            generator_seed: world.generator_metadata.seed,
            generator_index: world.generator_metadata.index,
            plan_length,
            episode,
            tokens,
            fingerprint: evidence.fingerprint,
        });
    }
    Ok(())
}

/// Lower one generated world to the generic G0 event boundary. The source of
/// learner-visible facts is exclusively the compiler's typed public seam.
/// Exact labels still come from the public contract query, not from private
/// term fields.
fn episode_for(world: &pretraining_term_compiler::CompiledWorld) -> Result<G0Episode, CorpusError> {
    let table = world.public_transition_table();
    let actions = public_actions(&table)?;
    let fallback_actions = table
        .rows
        .iter()
        .filter(|row| row.fallback)
        .map(|row| row.address.actuator)
        .collect::<BTreeSet<_>>();
    let mut action_plan = Vec::with_capacity(table.horizon);
    let mut selected_by_step = Vec::with_capacity(table.horizon);
    let mut prefix = Vec::new();
    for _ in 0..table.horizon {
        let selected = optimal_actions_from(&world.fragment, &world.contract, &prefix);
        if selected.is_empty() {
            return Err(CorpusError::Invalid(
                "generated world has no optimal action".into(),
            ));
        }
        let action = if let Some(action) = selected
            .iter()
            .copied()
            .find(|action| !fallback_actions.contains(action))
        {
            action
        } else if let Some(action) = selected
            .iter()
            .copied()
            .find(|action| fallback_actions.contains(action))
        {
            // A fallback is a public terminal action. Include its typed event
            // and stop the realized rollout rather than fabricating decisions
            // after the terminal boundary.
            action
        } else {
            return Err(CorpusError::Invalid(
                "optimal action is absent from public transition table".into(),
            ));
        };
        selected_by_step.push(selected);
        action_plan.push(action);
        prefix.push(action);
        if fallback_actions.contains(&action) {
            break;
        }
    }

    let view = world.public_event_view(&action_plan);
    let descriptors = world.public_ports();
    let schema = public_schema(&descriptors, &table, &view)?;
    let mut groups = vec![G0Group::new(transition_facts(&table)?)];
    let mut decisions = 0usize;
    for group in &view.groups {
        let opening_decision = if let PublicEventTime::BeforeAction { executed } = group.time {
            if executed != 0 || decisions != 0 {
                return Err(CorpusError::Invalid(format!(
                    "typed public event clock has an unexpected opening decision: {executed}"
                )));
            }
            Some(executed)
        } else {
            None
        };
        if let PublicEventTime::AfterAction { executed } = group.time {
            if executed == 0 || executed > table.horizon {
                return Err(CorpusError::Invalid(format!(
                    "typed public event clock is outside the scored horizon: {executed}"
                )));
            }
        }
        groups.push(G0Group::new(lower_public_events(group, &schema, &table)?));
        if let Some(executed) = opening_decision {
            groups.push(G0Group::new(query_facts(
                &actions,
                &selected_by_step[executed],
                table.horizon - executed,
            )));
            decisions += 1;
        }
        if let PublicEventTime::AfterAction { executed } = group.time {
            if executed < action_plan.len() {
                let next = executed;
                if decisions != next {
                    return Err(CorpusError::Invalid(format!(
                        "typed public event clock skipped decision {next}"
                    )));
                }
                groups.push(G0Group::new(query_facts(
                    &actions,
                    &selected_by_step[next],
                    table.horizon - next,
                )));
                decisions += 1;
            }
        }
    }
    if decisions != action_plan.len() {
        return Err(CorpusError::Invalid(format!(
            "typed public event view exposed {decisions} decisions for realized plan length {}",
            action_plan.len()
        )));
    }
    Ok(G0Episode::new(schema.schema, table.horizon, groups))
}

fn query_facts(actions: &[u16], selected: &[u16], remaining: usize) -> Vec<G0Fact> {
    actions
        .iter()
        .map(|actuator| G0Fact::ActionQuery {
            actuator: *actuator,
            remaining,
            selected: selected.contains(actuator),
        })
        .collect()
}

// The canonical condition ABI reserves a bounded integer code. Keep this
// marker above every finite G0 transition/restoration code while remaining
// within that public bound.
const FALLBACK_TAG_CODE: u16 = 4096;

fn public_actions(table: &PublicTransitionTable) -> Result<Vec<u16>, CorpusError> {
    let mut actions = table
        .rows
        .iter()
        .filter(|row| row.address.executed == 0 && row.address.source == 0)
        .map(|row| row.address.actuator)
        .collect::<Vec<_>>();
    actions.sort_unstable();
    actions.dedup();
    if actions.is_empty() {
        return Err(CorpusError::Invalid(
            "public transition table has no actions".into(),
        ));
    }
    Ok(actions)
}

fn transition_facts(table: &PublicTransitionTable) -> Result<Vec<G0Fact>, CorpusError> {
    let mut facts = Vec::with_capacity(table.rows.len());
    for row in &table.rows {
        let code = transition_code(table, row)?;
        if code == FALLBACK_TAG_CODE {
            return Err(CorpusError::UnsupportedPublicEvent(
                "transition address collides with fallback tag".into(),
            ));
        }
        facts.push(G0Fact::Condition {
            key: row.address.actuator,
            namespace: KeyNamespace::Actuator,
            code,
            value: normalized_state(row.destination, table.states),
            lower: 0.0,
            upper: 1.0,
        });
    }
    Ok(facts)
}

fn transition_code(
    table: &PublicTransitionTable,
    row: &pretraining_term_compiler::PublicTransition,
) -> Result<u16, CorpusError> {
    let code = row
        .address
        .executed
        .checked_mul(table.states)
        .and_then(|value| value.checked_add(row.address.source))
        .and_then(|value| value.checked_mul(2))
        .and_then(|value| value.checked_add(usize::from(row.fallback)))
        .and_then(|value| u16::try_from(value).ok())
        .ok_or_else(|| {
            CorpusError::UnsupportedPublicEvent(
                "transition address exceeds G0 condition code".into(),
            )
        })?;
    if code == FALLBACK_TAG_CODE {
        return Err(CorpusError::UnsupportedPublicEvent(
            "transition address collides with fallback tag".into(),
        ));
    }
    Ok(code)
}

#[derive(Debug, Clone)]
struct PublicSchemaData {
    schema: PortSchema,
    cell_ports: Vec<u16>,
    bounds: BTreeMap<u16, (f64, f64)>,
    descriptors: BTreeMap<u16, PortValue>,
}

fn public_schema(
    descriptors: &[PublicPortDescriptor],
    table: &PublicTransitionTable,
    view: &pretraining_term_compiler::PublicEventView,
) -> Result<PublicSchemaData, CorpusError> {
    let mut observations = Vec::new();
    let mut cell_ports = Vec::new();
    let mut bounds = BTreeMap::new();
    let mut descriptor_values = BTreeMap::new();
    for descriptor in descriptors {
        let key = descriptor.id.0;
        descriptor_values.insert(key, descriptor.value);
        match descriptor.value {
            PortValue::Cell => {
                let upper = table.states.saturating_sub(1) as f64;
                observations.push(Port {
                    key,
                    reference: 0.0,
                    lower: 0.0,
                    upper,
                });
                cell_ports.push(key);
                bounds.insert(key, (0.0, upper));
            }
            PortValue::Signal => {
                let (lower, upper) = signal_bounds(view, key);
                observations.push(Port {
                    key,
                    reference: 0.0,
                    lower,
                    upper,
                });
                bounds.insert(key, (lower, upper));
            }
            PortValue::Support => {
                return Err(CorpusError::UnsupportedPublicEvent(
                    "public support descriptors have no G0 representation".into(),
                ));
            }
            PortValue::Command => {}
        }
    }
    if observations.is_empty() {
        return Err(CorpusError::Invalid(
            "generated G0 world has no public observation channel".into(),
        ));
    }
    let actuators = table
        .rows
        .iter()
        .filter(|row| row.address.executed == 0 && row.address.source == 0)
        .map(|row| row.address.actuator)
        .collect::<BTreeSet<_>>()
        .into_iter()
        .map(Port::signed)
        .collect();
    Ok(PublicSchemaData {
        schema: PortSchema {
            observations,
            actuators,
        },
        cell_ports,
        bounds,
        descriptors: descriptor_values,
    })
}

fn signal_bounds(view: &pretraining_term_compiler::PublicEventView, key: u16) -> (f64, f64) {
    let mut lower = 0i64;
    let mut upper = 1i64;
    for event in view.groups.iter().flat_map(|group| group.events.iter()) {
        let value = match event {
            PublicEvent::Signal { port, value } if port.0 == key => Some(*value),
            PublicEvent::Observation {
                port,
                value: PublicEventValue::Scalar(value),
            } if port.0 == key => Some(*value),
            PublicEvent::RestorationAnnouncement { port, value, .. } if port.0 == key => {
                Some(*value)
            }
            _ => None,
        };
        if let Some(value) = value {
            lower = lower.min(value);
            upper = upper.max(value);
        }
    }
    (lower as f64, upper as f64)
}

fn lower_public_events(
    group: &PublicEventGroup,
    schema: &PublicSchemaData,
    table: &PublicTransitionTable,
) -> Result<Vec<G0Fact>, CorpusError> {
    let mut facts = Vec::new();
    for event in &group.events {
        match event {
            PublicEvent::Boundary(boundary) => facts.push(G0Fact::Boundary(match boundary {
                PublicBoundary::CalibrationReset => BoundarySubtype::CalibrationReset,
                PublicBoundary::TaskReset => BoundarySubtype::TaskReset,
                PublicBoundary::EpisodeEnd => BoundarySubtype::EpisodeEnd,
            })),
            PublicEvent::Observation { port, value } => {
                let key = port.0;
                let descriptor = schema.descriptors.get(&key).ok_or_else(|| {
                    CorpusError::UnsupportedPublicEvent(format!(
                        "observation refers to undeclared public port {key}"
                    ))
                })?;
                let content = match (descriptor, value) {
                    (PortValue::Cell, PublicEventValue::Cell(cell)) => {
                        let (lower, upper) = schema.bounds.get(&key).copied().ok_or_else(|| {
                            CorpusError::Invalid(format!("missing bounds for public port {key}"))
                        })?;
                        if (*cell as f64) < lower || (*cell as f64) > upper {
                            return Err(CorpusError::Invalid(format!(
                                "cell observation {cell} is outside public port {key} bounds"
                            )));
                        }
                        Content::Value {
                            value: *cell as f64,
                            lower,
                            upper,
                        }
                    }
                    (PortValue::Signal, PublicEventValue::Scalar(value)) => {
                        let (lower, upper) = schema.bounds.get(&key).copied().ok_or_else(|| {
                            CorpusError::Invalid(format!("missing bounds for public port {key}"))
                        })?;
                        Content::Value {
                            value: *value as f64,
                            lower,
                            upper,
                        }
                    }
                    (PortValue::Signal, PublicEventValue::Selection) => Content::Selection,
                    _ => {
                        return Err(CorpusError::UnsupportedPublicEvent(format!(
                            "typed observation value does not match public port {key}"
                        )))
                    }
                };
                facts.push(G0Fact::Observation { key, content });
            }
            PublicEvent::Goal { diagnostic } => {
                let SymbolicGoalDiagnostic::Atom(atom) = diagnostic else {
                    return Err(CorpusError::UnsupportedPublicEvent(
                        "composite public goals need a structured G0 goal carrier".into(),
                    ));
                };
                if atom.predicate != GoalPredicate::Settle {
                    return Err(CorpusError::UnsupportedPublicEvent(format!(
                        "public {:?} goal predicate has no faithful G0 carrier",
                        atom.predicate
                    )));
                }
                let [key] = schema.cell_ports.as_slice() else {
                    return Err(CorpusError::UnsupportedPublicEvent(
                        "a settle goal needs exactly one public cell port".into(),
                    ));
                };
                let (lower, upper) = schema.bounds[key];
                if (atom.cell as f64) < lower || (atom.cell as f64) > upper {
                    return Err(CorpusError::Invalid(format!(
                        "goal cell {} is outside public port {key} bounds",
                        atom.cell
                    )));
                }
                facts.push(G0Fact::Goal {
                    key: *key,
                    namespace: KeyNamespace::Observation,
                    content: Content::Value {
                        value: atom.cell as f64,
                        lower,
                        upper,
                    },
                });
            }
            PublicEvent::Signal { port, value } => {
                let key = port.0;
                if schema.descriptors.get(&key) != Some(&PortValue::Signal) {
                    return Err(CorpusError::UnsupportedPublicEvent(format!(
                        "signal refers to non-signal public port {key}"
                    )));
                }
                let (lower, upper) = schema.bounds[&key];
                facts.push(G0Fact::Observation {
                    key,
                    content: Content::Value {
                        value: *value as f64,
                        lower,
                        upper,
                    },
                });
            }
            PublicEvent::RestorationAnnouncement {
                port,
                actuator,
                activates_after,
                value,
            } => {
                let key = port.0;
                if schema.descriptors.get(&key) != Some(&PortValue::Signal) {
                    return Err(CorpusError::UnsupportedPublicEvent(format!(
                        "restoration announcement refers to non-signal public port {key}"
                    )));
                }
                let radix = table.horizon.checked_add(1).ok_or_else(|| {
                    CorpusError::UnsupportedPublicEvent("restoration timing radix overflows".into())
                })?;
                if *activates_after > table.horizon {
                    return Err(CorpusError::Invalid(format!(
                        "restoration activates after {activates_after}, beyond horizon {}",
                        table.horizon
                    )));
                }
                let code = (*actuator as usize)
                    .checked_mul(radix)
                    .and_then(|value| value.checked_add(*activates_after))
                    .and_then(|value| u16::try_from(value).ok())
                    .ok_or_else(|| {
                        CorpusError::UnsupportedPublicEvent(
                            "restoration identity exceeds G0 condition code".into(),
                        )
                    })?;
                let (lower, upper) = schema.bounds[&key];
                facts.push(G0Fact::Condition {
                    key,
                    namespace: KeyNamespace::Observation,
                    code,
                    value: *value as f64,
                    lower,
                    upper,
                });
            }
            PublicEvent::ActionExecuted { actuator, fallback } => {
                facts.push(G0Fact::ActionExecuted {
                    actuator: *actuator,
                });
                if *fallback {
                    facts.push(G0Fact::Condition {
                        key: *actuator,
                        namespace: KeyNamespace::Actuator,
                        code: FALLBACK_TAG_CODE,
                        value: 1.0,
                        lower: 0.0,
                        upper: 1.0,
                    });
                }
            }
        }
    }
    Ok(facts)
}

/// Match the finite G0 payload's f32 precision before handing the value to
/// the renderer. This keeps non-power-of-two state counts (for example 5)
/// exactly invertible under the existing float ABI while retaining the
/// destination/state-count normalization.
fn normalized_state(destination: usize, states: usize) -> f64 {
    (destination as f32 / states as f32) as f64
}

#[cfg(test)]
mod tests {
    use super::*;
    use pretraining_term_compiler::{G0FeatureSchedule, G0Topology, PlanLengthDistribution};

    fn specs() -> (G0CorpusSpec, G0CorpusSpec) {
        (
            G0CorpusSpec {
                seed: 1,
                count: 4,
                min_states: 4,
                max_states: 5,
                min_horizon: 2,
                max_horizon: 2,
                topology: G0Topology::Mixed,
                feature_schedule: G0FeatureSchedule::Coverage,
                plan_length_distribution: PlanLengthDistribution {
                    weights: vec![1, 1],
                },
            },
            G0CorpusSpec {
                seed: 13,
                count: 4,
                min_states: 7,
                max_states: 8,
                min_horizon: 2,
                max_horizon: 2,
                topology: G0Topology::Mixed,
                feature_schedule: G0FeatureSchedule::Coverage,
                plan_length_distribution: PlanLengthDistribution {
                    weights: vec![1, 1],
                },
            },
        )
    }

    #[test]
    fn corpus_is_replayable_disjoint_and_one_example_per_world() {
        let (train, held_out) = specs();
        let first = generate_corpus(train.clone(), held_out.clone()).expect("corpus");
        let second = generate_corpus(train, held_out).expect("replay");
        assert_eq!(first, second);
        assert_eq!(first.examples.len(), 8);
        assert_eq!(first.train().count(), 4);
        assert_eq!(first.held_out().count(), 4);
        let train_hashes: BTreeSet<_> = first.train().map(|item| &item.semantic_hash).collect();
        let held_hashes: BTreeSet<_> = first.held_out().map(|item| &item.semantic_hash).collect();
        assert!(train_hashes.is_disjoint(&held_hashes));
        assert!(first
            .examples
            .iter()
            .all(|item| item.episode.decisions() == item.episode.horizon));
        assert!(first.examples.iter().all(|item| item
            .tokens
            .iter()
            .any(|token| token.action_mask.iter().any(|value| *value))));
        assert!(first
            .examples
            .iter()
            .all(|item| (1..=item.episode.horizon).contains(&item.plan_length)));
        let realized_plans = first.examples.iter().fold(
            std::collections::BTreeMap::<usize, usize>::new(),
            |mut histogram, item| {
                *histogram.entry(item.plan_length).or_default() += 1;
                histogram
            },
        );
        assert_eq!(realized_plans.values().sum::<usize>(), first.examples.len());
        let first_episode = &first.examples[0].episode;
        let first_query = first_episode
            .groups
            .iter()
            .position(|group| {
                group
                    .facts
                    .iter()
                    .any(|fact| matches!(fact, G0Fact::ActionQuery { .. }))
            })
            .expect("first query");
        assert!(first_episode.groups[..first_query].iter().any(|group| {
            group
                .facts
                .iter()
                .any(|fact| matches!(fact, G0Fact::Boundary(BoundarySubtype::TaskReset)))
        }));
        assert!(first_episode.groups[..first_query].iter().any(|group| {
            group
                .facts
                .iter()
                .any(|fact| matches!(fact, G0Fact::Goal { .. }))
        }));
        assert!(!first
            .learner_tokens(Split::Train)
            .expect("tokens")
            .is_empty());
    }

    #[test]
    fn overlap_is_refused_as_a_false_holdout() {
        let spec = G0CorpusSpec {
            seed: 2,
            count: 1,
            topology: G0Topology::Ring,
            feature_schedule: G0FeatureSchedule::Coverage,
            min_states: 5,
            max_states: 5,
            min_horizon: 2,
            max_horizon: 2,
            plan_length_distribution: PlanLengthDistribution {
                weights: vec![1, 1],
            },
        };
        assert!(matches!(
            generate_corpus(spec.clone(), spec),
            Err(CorpusError::StructuralOverlap { .. })
        ));
    }

    #[test]
    fn artifact_round_trips_and_tokens_reenter_the_production_boundary() {
        let (train, held_out) = specs();
        let artifact = generate_corpus(train, held_out).expect("corpus");
        let bytes = serde_json::to_vec(&artifact).expect("artifact serializes");
        let decoded: CorpusArtifact = serde_json::from_slice(&bytes).expect("artifact decodes");
        assert_eq!(artifact, decoded);
        assert!(decoded
            .learner_tokens(Split::HeldOut)
            .expect("learner tokens")
            .iter()
            .all(|token| token.public.role as u8 <= 10));
    }

    #[test]
    fn changing_a_transition_changes_the_public_fingerprint_before_the_first_query() {
        let spec = G0CorpusSpec {
            seed: 41,
            count: 1,
            topology: G0Topology::Graph,
            feature_schedule: G0FeatureSchedule::Coverage,
            min_states: 5,
            max_states: 5,
            min_horizon: 2,
            max_horizon: 2,
            plan_length_distribution: PlanLengthDistribution {
                weights: vec![1, 1],
            },
        };
        let original = spec.generate().expect("world").remove(0);
        let original_compiled = original.compile().expect("compiles");
        let original_episode = episode_for(&original_compiled).expect("episode");
        let original_evidence = boundary_check(&original_episode).expect("boundary");

        let mut changed = original.clone();
        if let pretraining_term_compiler::StateSpaceTerm::Graph {
            transitions,
            states,
            ..
        } = &mut changed.term.environment.state_space
        {
            let edge = transitions
                .iter_mut()
                .find(|edge| edge.actuator == 0)
                .expect("advance edge");
            edge.destination = (edge.destination + 1) % *states;
        } else {
            panic!("test requested graph world");
        }
        let changed_compiled = changed.compile().expect("changed world compiles");
        let changed_episode = episode_for(&changed_compiled).expect("episode");
        let changed_evidence = boundary_check(&changed_episode).expect("boundary");
        let original_tokens = profiled_tokens(&original_episode).expect("tokens");
        let changed_tokens = profiled_tokens(&changed_episode).expect("tokens");
        assert_ne!(
            original_evidence.fingerprint, changed_evidence.fingerprint,
            "dynamics must affect learner-visible support before a query"
        );
        assert_ne!(original_tokens, changed_tokens);
        let first_query_token = original_tokens
            .iter()
            .position(|token| token.public.role == Role::ActionQuery)
            .expect("query token");
        assert!(first_query_token > 0);
        assert_eq!(
            first_query_token,
            changed_tokens
                .iter()
                .position(|token| token.public.role == Role::ActionQuery)
                .expect("query token")
        );
        assert_ne!(
            &original_tokens[..first_query_token],
            &changed_tokens[..first_query_token]
        );
        let first_query = original_episode
            .groups
            .iter()
            .position(|group| {
                group
                    .facts
                    .iter()
                    .any(|fact| matches!(fact, G0Fact::ActionQuery { .. }))
            })
            .expect("query");
        assert!(original_episode.groups[..first_query]
            .iter()
            .any(|group| group
                .facts
                .iter()
                .any(|fact| matches!(fact, G0Fact::Condition { .. }))));
    }

    #[test]
    fn public_dynamics_cover_every_step_and_teacher_labels_use_the_same_contract() {
        let spec = G0CorpusSpec {
            seed: 53,
            count: 1,
            topology: G0Topology::Mixed,
            feature_schedule: G0FeatureSchedule::Coverage,
            min_states: 4,
            max_states: 6,
            min_horizon: 2,
            max_horizon: 3,
            plan_length_distribution: PlanLengthDistribution {
                weights: vec![1, 1, 1],
            },
        };
        let generated = spec.generate().expect("world").remove(0);
        let compiled = generated.compile().expect("compiles");
        let episode = episode_for(&compiled).expect("episode");
        let table = compiled.public_transition_table();
        let states = table.states;
        let mut conditions = std::collections::BTreeMap::new();
        for fact in episode.groups.iter().flat_map(|group| group.facts.iter()) {
            if let G0Fact::Condition {
                key,
                namespace: KeyNamespace::Actuator,
                code,
                value,
                ..
            } = fact
            {
                conditions.insert((*key, *code as usize), *value);
            }
        }
        assert_eq!(conditions.len(), table.rows.len());
        for row in &table.rows {
            let code = transition_code(&table, row).expect("transition code");
            let published = conditions
                .get(&(row.address.actuator, code as usize))
                .expect("published transition");
            assert_eq!(*published, normalized_state(row.destination, states));
        }

        let mut prefix = Vec::new();
        for group in &episode.groups {
            let queries: Vec<(u16, bool)> = group
                .facts
                .iter()
                .filter_map(|fact| match fact {
                    G0Fact::ActionQuery {
                        actuator, selected, ..
                    } => Some((*actuator, *selected)),
                    _ => None,
                })
                .collect();
            if queries.is_empty() {
                continue;
            }
            let expected = optimal_actions_from(&compiled.fragment, &compiled.contract, &prefix);
            let taught: Vec<u16> = queries
                .iter()
                .filter_map(|(action, selected)| selected.then_some(*action))
                .collect();
            assert_eq!(taught, expected);
            prefix.push(taught[0]);
        }
    }

    #[test]
    fn transition_encoding_keeps_time_source_and_fallback_distinct() {
        let table = PublicTransitionTable {
            states: 2,
            horizon: 1,
            rows: vec![
                pretraining_term_compiler::PublicTransition {
                    address: pretraining_term_compiler::PublicTransitionAddress {
                        executed: 0,
                        source: 0,
                        actuator: 7,
                    },
                    destination: 1,
                    fallback: false,
                },
                pretraining_term_compiler::PublicTransition {
                    address: pretraining_term_compiler::PublicTransitionAddress {
                        executed: 1,
                        source: 0,
                        actuator: 7,
                    },
                    destination: 1,
                    fallback: false,
                },
                pretraining_term_compiler::PublicTransition {
                    address: pretraining_term_compiler::PublicTransitionAddress {
                        executed: 0,
                        source: 0,
                        actuator: 7,
                    },
                    destination: 1,
                    fallback: true,
                },
            ],
        };
        let facts = transition_facts(&table).expect("transition facts");
        let codes: BTreeSet<_> = facts
            .iter()
            .filter_map(|fact| match fact {
                G0Fact::Condition { code, .. } => Some(*code),
                _ => None,
            })
            .collect();
        assert_eq!(codes.len(), table.rows.len());
    }

    #[test]
    fn same_valued_distinct_public_signal_ports_remain_distinct() {
        let table = PublicTransitionTable {
            states: 2,
            horizon: 1,
            rows: vec![pretraining_term_compiler::PublicTransition {
                address: pretraining_term_compiler::PublicTransitionAddress {
                    executed: 0,
                    source: 0,
                    actuator: 0,
                },
                destination: 0,
                fallback: false,
            }],
        };
        let descriptors = vec![
            pretraining_term_compiler::PublicPortDescriptor {
                id: pretraining_term_compiler::PublicPortId(3),
                direction: pretraining_term_compiler::PortDirection::Output,
                value: PortValue::Signal,
            },
            pretraining_term_compiler::PublicPortDescriptor {
                id: pretraining_term_compiler::PublicPortId(7),
                direction: pretraining_term_compiler::PortDirection::Output,
                value: PortValue::Signal,
            },
        ];
        let view = pretraining_term_compiler::PublicEventView {
            groups: vec![pretraining_term_compiler::PublicEventGroup {
                time: PublicEventTime::BeforeAction { executed: 0 },
                events: vec![
                    PublicEvent::Signal {
                        port: pretraining_term_compiler::PublicPortId(3),
                        value: 5,
                    },
                    PublicEvent::Signal {
                        port: pretraining_term_compiler::PublicPortId(7),
                        value: 5,
                    },
                ],
            }],
        };
        let schema = public_schema(&descriptors, &table, &view).expect("schema");
        let facts = lower_public_events(&view.groups[0], &schema, &table).expect("events");
        let keys: Vec<_> = facts
            .iter()
            .filter_map(|fact| match fact {
                G0Fact::Observation { key, .. } => Some(*key),
                _ => None,
            })
            .collect();
        assert_eq!(keys, vec![3, 7]);
    }
}
